name: AntiInterrupt
version: '${project.version}'
main: me.jass.antiinterrupt.AntiInterrupt
api-version: 1.19
authors: [Jass]
softdepend: [WorldGuard]
description: Blocks Interrupters in a 1v1 PvP Setting
